env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {
  "react/react-in-jsx-scope": "off",
<<<<<<< HEAD
  "react/jsx-filename-extension": [ 1, { "extensions": [ ".js", ".jsx" ] } ],
=======
  "react/jsx-filename-extension": "off",
>>>>>>> 197406b87a494bd63d9c32a0e1392849df111bff
  "react/prop-types": "off",
  "linebreak-style": 0
}
